version: '3'
services:
  app:
    container_name: hightly
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '5000:5000'
      - '5001:5001'
      - '5002:5002'